import { createApp } from 'vue';
import './style.css';
import './buffer';
import 'crypto';
import axios from 'axios';
import App from './Sign712Message.vue';
//import App from './SignPersonalMessage.vue';
//import App from './SIgnTip712Message.vue';
window.axios = axios;
createApp(App).mount('#app');
